name: Genera PDF CorsoCSS

on:
  push:
    branches: [ main ]
    paths:
      - 'slide/*.*'
      - '.github/workflows/generatepdf.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

    - name: Generate pdf
      run: |
        cd slide
        cp 'CorsoCSS.md' 'CorsoCSS-backup.md'
        sed -i "s/%date%/$(date +'%Y-%m-%d')/g" 'CorsoCSS.md'
        sed -i "s/%time%/$(date +'%H:%M')/g" 'CorsoCSS.md'
        npx @marp-team/marp-cli@latest 'CorsoCSS.md' --pdf --allow-local-files --pdf-outlines --pdf-outlines.pages=false
        rm 'CorsoCSS.md'
        mv 'CorsoCSS-backup.md' 'CorsoCSS.md'

    - name: commit & push
      run: |
        git add -A
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update slides"
        git push

